version: '3'
services:
  amqp-broker:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
  ocpp-db:
    image: citrineos/postgres:preseeded
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: citrine
      POSTGRES_USER: citrine
      POSTGRES_PASSWORD: 'citrine'
  redis:
    build:
      context: ..
      dockerfile: .redis.Dockerfile
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./data/directus/uploads:/directus/uploads
      - ./data/directus/extensions:/directus/extensions
    environment:
      KEY: '1234567890'
      SECRET: '0987654321'
      ADMIN_EMAIL: 'admin@citrineos.com'
      ADMIN_PASSWORD: 'CitrineOS!'
      DB_CLIENT: 'pg'
      DB_HOST: ocpp-db
      DB_PORT: 5432
      DB_DATABASE: 'citrine'
      DB_USER: 'citrine'
      DB_PASSWORD: 'citrine'
      WEBSOCKETS_ENABLED: 'true'
  citrine:
    build:
      context: ..
      dockerfile: ./Server/deploy.Dockerfile
    depends_on:
      ocpp-db:
        condition: service_started
      amqp-broker:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    expose:
      - 8080-8082
    environment:
      CITRINEOS_UTIL_DIRECTUS_TOKEN: '-ssaT85n4S-wVD21LKOCDwvXN5PtnJc0'
      APP_NAME: 'general'
  certificates:
    build:
      context: ..
      dockerfile: ./Server/deploy.Dockerfile
    depends_on:
      ocpp-db:
        condition: service_started
      amqp-broker:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8083:8083
    expose:
      - 8083
    environment:
      CITRINEOS_UTIL_DIRECTUS_TOKEN: '-ssaT85n4S-wVD21LKOCDwvXN5PtnJc0'
      APP_NAME: 'certificates'
  configuration:
    build:
      context: ../..
      dockerfile: .deploy.Dockerfile
    depends_on:
      ocpp-db:
        condition: service_started
      amqp-broker:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8084:8084
    expose:
      - 8084
    volumes:
      - ./:/usr/configuration
      - /usr/configuration/node_modules
    environment:
      CITRINEOS_UTIL_DIRECTUS_TOKEN: '-ssaT85n4S-wVD21LKOCDwvXN5PtnJc0'
      APP_NAME: 'configuration'
  evdriver:
    build:
      context: ../..
      dockerfile: .deploy.Dockerfile
    depends_on:
      ocpp-db:
        condition: service_started
      amqp-broker:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8085:8085
    expose:
      - 8085
    volumes:
      - ./:/usr/evdriver
      - /usr/evdriver/node_modules
    environment:
      CITRINEOS_UTIL_DIRECTUS_TOKEN: '-ssaT85n4S-wVD21LKOCDwvXN5PtnJc0'
      APP_NAME: 'evdriver'
  monitoring:
    build:
      context: ../..
      dockerfile: .deploy.Dockerfile
    depends_on:
      ocpp-db:
        condition: service_started
      amqp-broker:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8086:8086
    expose:
      - 8086
    volumes:
      - ./:/usr/monitoring
      - /usr/monitoring/node_modules
    environment:
      CITRINEOS_UTIL_DIRECTUS_TOKEN: '-ssaT85n4S-wVD21LKOCDwvXN5PtnJc0'
      APP_NAME: 'monitoring'
  reporting:
    build:
      context: ../..
      dockerfile: .deploy.Dockerfile
    depends_on:
      ocpp-db:
        condition: service_started
      amqp-broker:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8087:8087
    expose:
      - 8087
    volumes:
      - ./:/usr/reporting
      - /usr/reporting/node_modules
    environment:
      CITRINEOS_UTIL_DIRECTUS_TOKEN: '-ssaT85n4S-wVD21LKOCDwvXN5PtnJc0'
      APP_NAME: 'reporting'
  smartcharging:
    build:
      context: ../..
      dockerfile: .deploy.Dockerfile
    depends_on:
      ocpp-db:
        condition: service_started
      amqp-broker:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8088:8088
    expose:
      - 8088
    volumes:
      - ./:/usr/smartcharging
      - /usr/smartcharging/node_modules
    environment:
      CITRINEOS_UTIL_DIRECTUS_TOKEN: '-ssaT85n4S-wVD21LKOCDwvXN5PtnJc0'
      APP_NAME: 'smartcharging'
  tenant:
    build:
      context: ../..
      dockerfile: .deploy.Dockerfile
    depends_on:
      ocpp-db:
        condition: service_started
      amqp-broker:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8089:8089
    expose:
      - 8089
    volumes:
      - ./:/usr/tenant
      - /usr/tenant/node_modules
    environment:
      CITRINEOS_UTIL_DIRECTUS_TOKEN: '-ssaT85n4S-wVD21LKOCDwvXN5PtnJc0'
      APP_NAME: 'tenant'
  transactions:
    build:
      context: ../..
      dockerfile: .deploy.Dockerfile
    depends_on:
      ocpp-db:
        condition: service_started
      amqp-broker:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8090:8090
    expose:
      - 8090
    volumes:
      - ./:/usr/transactions
      - /usr/transactions/node_modules
    environment:
      CITRINEOS_UTIL_DIRECTUS_TOKEN: '-ssaT85n4S-wVD21LKOCDwvXN5PtnJc0'
      APP_NAME: 'transactions'
